I have added the speedTestGo
MirageCloud/Mirage pull request #12
Opened 2024-04-12 07:36 UTC by kunal-511

I have added the speedTestGo

2024-04-13 07:26 UTC, kunal-511 commented
Please review this PR request

2024-04-13 07:33 UTC, Pushkarm029 requested changes

2024-04-13 07:33 UTC, Pushkarm029 commented on speed test/main.go
> +		lesgo = append(lesgo, result)
Variable name can be improved.

2024-04-13 07:33 UTC, Pushkarm029 commented on speed test/main.go
> +	var speedtestClient = speedtest.New()
Please consider factory type architecture.

2024-04-13 07:33 UTC, Pushkarm029 commented on speed test/main.go
> +	"github.com/showwin/speedtest-go/speedtest"
Add this comment here

TODO: Remove this third party library later

2024-04-13 07:33 UTC, Pushkarm029 commented on speed test/main.go
> +	log.Fatal(http.ListenAndServe(":8080", nil))
Use Uber Zap instead

2024-04-13 07:33 UTC, Pushkarm029 commented on speed test/main.go
> +		err = s.DownloadTest()
Can we add tests?

2024-04-13 13:00 UTC, kunal-511 commented
@Pushkarm029  I have resolved all the issues raised by you now. But test is missing I will add them shortly

2024-04-13 13:01 UTC, Pushkarm029 commented
@kunal-511 good

2024-04-15 09:23 UTC, kunal-511 commented
Test cases have now been added.
Please merge this also @Pushkarm029

2024-04-15 09:27 UTC, Pushkarm029 requested changes

2024-04-15 09:27 UTC, Pushkarm029 commented on speedTest/main.go
> +func TestSpeedtestHandler(t *testing.T) {
move this into a new file `package_test.go`

2024-04-15 09:27 UTC, Pushkarm029 commented on speedTest/main.go
> +func TestFormatSpeed(t *testing.T) {
same

2024-04-15 09:27 UTC, Pushkarm029 commented on speedTest/main.go
> +	go main()
why starting goroutine?

2024-04-18 20:04 UTC, Pushkarm029 approved these changes

2024-04-18 20:04 UTC, merged

2024-04-18 20:04 UTC, Pushkarm029 commented
Thanks🎉